name: Scala CI

on:
   push:
      branches: [master]
   pull request:

jobs:
   build:
     runs-on: ubuntu-latest

     steps:
     - uses: actions/checkout@v2
     - name: Setup Scala utils
        uses: olafurpg/setup-scala@v11
        with:
           java-versions: adopt@1.8
    - name: Build and Test and Validate
      run: sbt -v -Dfile.encoding=UTF-8 +test
  publish:
      runs-on: ubuntu-latest
      if: github.ref == 'refs/heads/main'

      steps:
      - uses: actions/checkout@v2
      - name: setup scala utils
        uses: olafurpg/setup-scala@v11
        with:
           java-veresion: adopt@1.8
      - name: Build and Test and generate
      run: sbt -v -Dfile.encoding=UTF-8 clean assembly

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
        aws-access-key-id: ${{ secret.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secret.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
      -name: Upload artifact to S3
       run: find ./ -name '*jar' |grep spark-engine| xargs -I{} echo"aws s3 cp {} s3://spark-scala-project/"|bash
       